apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
  name: ci-storage
provisioner: kubernetes.io/aws-ebs 
parameters: 
   type: gp2 
reclaimPolicy: Retain 
allowVolumeExpansion: true 
mountOptions: 
  - debug 
volumeBindingMode: Immediate
