# This Secret is used to authenticate to the dcgs-registry where images are stored
# To use your own credentials, you need to base64 encode your config.json file
# usually located here on Mac /Users/<your username here>/.docker/config.json.
# To encode the file and get the output use the following command: 
# openssl base64 -in /Users/<username>/.docker/config.json -out /Users/<username>/.docker/config_base64.txt
# Then copy the content inside the config_base64.txt file and paste it as the value for .dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuaGFhcy0yMzkucGV6LnBpdm90YWwuaW8iOiB7fSwKCQkiaHR0cHM6Ly9oYXJib3IuaGFhcy0yMzkucGV6LnBpdm90YWwuaW8iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4yIChkYXJ3aW4pIgoJfSwKCSJjcmVkc1N0b3JlIjogIm9zeGtleWNoYWluIiwKCSJzdGFja09yY2hlc3RyYXRvciI6ICJzd2FybSIKfQ==
type: kubernetes.io/dockerconfigjson
